Controllers/MonedasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PrimerProyecto.Models;

namespace PrimerProyecto.Controllers
{
    public class MonedasController : Controller
    {
        private PrimerProyectoEntities1 db = new PrimerProyectoEntities1();

        // GET: Monedas
        public ActionResult Index()
        {
            return View(db.Monedas.ToList());
        }

        // GET: Monedas/Details/5
        public ActionResult Details(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Monedas monedas = db.Monedas.Find(id);
            if (monedas == null)
            {
                return HttpNotFound();
            }
            return View(monedas);
        }

        // GET: Monedas/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Monedas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,Codigo,Nombre,Valor,Descripcion")] Monedas monedas)
        {
            if (ModelState.IsValid)
            {
                db.Monedas.Add(monedas);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(monedas);
        }

        // GET: Monedas/Edit/5
        public ActionResult Edit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Monedas monedas = db.Monedas.Find(id);
            if (monedas == null)
            {
                return HttpNotFound();
            }
            return View(monedas);
        }

        // POST: Monedas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,Codigo,Nombre,Valor,Descripcion")] Monedas monedas)
        {
            if (ModelState.IsValid)
            {
                db.Entry(monedas).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(monedas);
        }

        // GET: Monedas/Delete/5
        public ActionResult Delete(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Monedas monedas = db.Monedas.Find(id);
            if (monedas == null)
            {
                return HttpNotFound();
            }
            return View(monedas);
        }

        // POST: Monedas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(long id)
        {
            Monedas monedas = db.Monedas.Find(id);
            db.Monedas.Remove(monedas);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/TrazabilidadsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PrimerProyecto.Models;

namespace PrimerProyecto.Controllers
{
    public class TrazabilidadsController : Controller
    {
        private PrimerProyectoEntities1 db = new PrimerProyectoEntities1();

        // GET: Trazabilidads
        public ActionResult Index()
        {
            var trazabilidad = db.Trazabilidad.Include(t => t.Embarques).Include(t => t.Procesos);
            return View(trazabilidad.ToList());
        }

        // GET: Trazabilidads/Details/5
        public ActionResult Details(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Trazabilidad trazabilidad = db.Trazabilidad.Find(id);
            if (trazabilidad == null)
            {
                return HttpNotFound();
            }
            return View(trazabilidad);
        }

        // GET: Trazabilidads/Create
        public ActionResult Create()
        {
            ViewBag.idEmbarques = new SelectList(db.Embarques, "id", "Direccion_pro");
            ViewBag.idProcesos = new SelectList(db.Procesos, "id", "Nombre");
            return View();
        }

        // POST: Trazabilidads/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,Tipo,Kilos,Teus,Competencia,Otra_Competencia,Cod_Envio,Pais_Origen,Ciudad_Origen,Pais_Destino,Cuidad_Destino,Via,idProcesos,idEmbarques")] Trazabilidad trazabilidad)
        {
            if (ModelState.IsValid)
            {
                db.Trazabilidad.Add(trazabilidad);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.idEmbarques = new SelectList(db.Embarques, "id", "Direccion_pro", trazabilidad.idEmbarques);
            ViewBag.idProcesos = new SelectList(db.Procesos, "id", "Nombre", trazabilidad.idProcesos);
            return View(trazabilidad);
        }

        // GET: Trazabilidads/Edit/5
        public ActionResult Edit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Trazabilidad trazabilidad = db.Trazabilidad.Find(id);
            if (trazabilidad == null)
            {
                return HttpNotFound();
            }
            ViewBag.idEmbarques = new SelectList(db.Embarques, "id", "Direccion_pro", trazabilidad.idEmbarques);
            ViewBag.idProcesos = new SelectList(db.Procesos, "id", "Nombre", trazabilidad.idProcesos);
            return View(trazabilidad);
        }

        // POST: Trazabilidads/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,Tipo,Kilos,Teus,Competencia,Otra_Competencia,Cod_Envio,Pais_Origen,Ciudad_Origen,Pais_Destino,Cuidad_Destino,Via,idProcesos,idEmbarques")] Trazabilidad trazabilidad)
        {
            if (ModelState.IsValid)
            {
                db.Entry(trazabilidad).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.idEmbarques = new SelectList(db.Embarques, "id", "Direccion_pro", trazabilidad.idEmbarques);
            ViewBag.idProcesos = new SelectList(db.Procesos, "id", "Nombre", trazabilidad.idProcesos);
            return View(trazabilidad);
        }

        // GET: Trazabilidads/Delete/5
        public ActionResult Delete(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Trazabilidad trazabilidad = db.Trazabilidad.Find(id);
            if (trazabilidad == null)
            {
                return HttpNotFound();
            }
            return View(trazabilidad);
        }

        // POST: Trazabilidads/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(long id)
        {
            Trazabilidad trazabilidad = db.Trazabilidad.Find(id);
            db.Trazabilidad.Remove(trazabilidad);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <script src="~/Scripts/jquery-3.6.0.min.js"></script>
    <script src="~/Scripts/materialize/js/materialize.js"></script>
    <link href="~/Scripts/materialize/css/materialize.css" rel="stylesheet" />
    <script src="~/Scripts/funcionalidades.js"></script>
    <link href="~/Content/Principal.css" rel="stylesheet" />
    <link rel="preconnect" href="https://fonts.gstatic.com"> @*para traer las fuentes*@
    <link href="https://fonts.googleapis.com/css2?family=Akaya+Telivigala&display=swap" rel="stylesheet">
    @*<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Tangerine">*@
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

</head>

<body>
    <div class="row fondo">
        <!--Header o parte superior -->
        <div class="col s12 center ">
            <img class="imagen" src="~/Imagen/Cargo.png" height="120" width="695" /> @* ~/lo uso para ubicarme en la raiz del proyecto*@
        </div>
        
    </div>

    <div class="row">
        <div class="col s3 center">
            <ul>
                <li class="li"> @Html.ActionLink("Usuarios", "Index", "Usuarios")  @*<a href="#">Usuarios</a>*@
                </li>

                <li class="li">
                    @Html.ActionLink("Procesos", "Index", "Procesos")
                </li>

                <li class="li">
                    @Html.ActionLink("Actividades", "Index", "Actividades")
                </li>

                <li class="li">
                    
                    @Html.ActionLink("Embarques", "Index", "Embarques")
                </li>
                <li class="li">
                     
                    @Html.ActionLink("Trazabilidad", "Index", "Trazabilidads")
                </li>
                <li class="li">
                    
                    @Html.ActionLink("Moneda", "Index", "Monedas")
                </li>
            </ul>
        </div>
        <div class="col s7 center">
            @RenderBody()

        </div>
    </div>

    <div class="row fondo footer">
        <div class="col s6  right-align">
            <ul>
                <li>Estamos ubicados en Anserma y Riosucio, Caldas, Colombia</li>
                <li>Telefono: +57 6 8890012</li>
                <li>&copy; 2021</li>
            </ul>
        </div>

        <div class="col s6 ">
            <i class="material-icons medium">facebook</i>
            <i class="material-icons medium">contact_mail</i>
            <i class="material-icons medium">phone_in_talk</i>
            <i class="material-icons medium">qr_code_2</i>
            @*<img src="https://img.icons8.com/windows/80/ffffff/whatsapp-squared.png" />*@



            @*<ul>
            <li> </li>

            <li>Twitter</li>
            <li>Instagram</li>
        </ul>*@
        </div>
        
    </div>

</body>
</html>